In [1]:
import numpy as np

 Go and collect data about a shopping curt,
 i.Create a matrix of tomatoes,onions,garlic,carrots
 ii.Create another matrix for the amount;
 after;(a) Multipy
 (b) transpose one of the matrix and multipy
 (c) Multiply the two by an identity matrix
 (d) Check to see if they are linear dependent or independent
 (e) Find the determinant

In [32]:
# matrix of items
B = np.array([1,2,3,2,5,1,0,2,3,5,3,5,1,3,1,2])
items = B.reshape(4,4)
print(items)
np.ndim(items)

[[1 2 3 2]
 [5 1 0 2]
 [3 5 3 5]
 [1 3 1 2]]


2

In [33]:
# matrix of prices
Prices = np.array([200,100,100,150])
print(Prices.reshape(4,1))
np.ndim(Prices)


[[200]
 [100]
 [100]
 [150]]


1

In [34]:
# multiply matries
np.matmul(items,Prices)

array([1000, 1400, 2150,  900])

In [41]:
# transpose
matrix_T=(np.transpose(items))
print(matrix_T)

[[1 5 3 1]
 [2 1 5 3]
 [3 0 3 1]
 [2 2 5 2]]


In [31]:
#multiplying with the transposed one
items@matrix_T


array([[18, 11, 32, 14],
       [11, 30, 30, 12],
       [32, 30, 68, 31],
       [14, 12, 31, 15]])

In [35]:
# an identity matrix
identity_m=np.eye(4,4)
print(identity_m)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
#multipling with the identity matrix
items@identity_m

array([[1., 2., 3., 2.],
       [5., 1., 0., 2.],
       [3., 5., 3., 5.],
       [1., 3., 1., 2.]])

In [42]:
# multipling the identity and transposed matrix
identity_m@matrix_T

array([[1., 5., 3., 1.],
       [2., 1., 5., 3.],
       [3., 0., 3., 1.],
       [2., 2., 5., 2.]])

In [43]:
#determinate of a matrix of items
np.linalg.det(items)

-31.0

In [44]:
#determinant of a transposed matrix
np.linalg.det(matrix_T)

-30.999999999999986

In [ ]:
# THEREFORE MATRIX OF ITEMS AND THE TRANSPOSED MATRIX ARE LINEARLY INDEPENDENT BECAUSE THERE DETERMINANTS ARE LESS THAN ZERO.